spring.application.name=PZ2
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/webprojekat?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=ZmFrc0lUMzU1V2ViU2lzdGVtaTJTZWNyZXRLZXlGb3JKd3RTaWduaW5nMTIzNDU2
jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
